### ISSUE TITLE
Change wording of first bullet

### ISSUE THREAD

**Issue by aakoch** [sdd-manifesto/manifesto#11]
Currently the first major point reads as "Software Defined Delivery is: Core". I believe this should be a verb or an adjective as the other points are. It doesn't flow since it is a noun after the verb "is" without an article preceding it.

**Comment by wcrowley-clgx** [comment]
@aakoch 
I disagree. I think in the context, the noun "core" is acting like an adjective.  Many nouns can do this.
Software Defined Delivery is core to a team and organization. It's saying you should follow the 3 bullets to achieve core delivery, as opposed to perfunctory delivery.

Unless you have a particular adjective that better expresses the point? Better to provide solutions than point out problems.

Checking my thesaurus, you might like "central" better ...but that seems like a style choice. I like "core" better.

**Comment by aakoch** [comment]
I appreciate the reply and feel satisfied with that answer. Thanks, @wcrowley-clgx!
